fromFile: 
  enabled: false
  fileName: video.avi

saveOriginal: 
  enabled: true
  fileName: video.avi

saveResult: 
  enabled: true
  fileName: result.avi

ballRadius: 3.5

cameraMatrix:
  - [ 473.47735154, 0, 340.74974772 ]
  - [ 0, 473.65574398, 228.11903207 ]
  - [ 0, 0, 1 ]

distCoeffs:
  - -0.09308854
  - 0.35950345
  - -0.00096885
  - -0.0017941
  - -0.40272195

denoisingStrength: 20
kernelSize: 9

houghCircle:
  minDist: 100
  minRadius: 25
  maxRadius: 300
  param1: 68
  param2: 0.80